### ISSUE TITLE
Create a full suite of unit tests

### ISSUE THREAD

**Issue by jamesdavis12** [SCCapstone/CapiStonsker#300]
- [x] Come up with a list of functions to be tested via unit testing
- [x] Write unit tests, ensure boundary conditions are being tested
- [x] Make sure unit tests can easily be run from the Android Studio command line
- [x] Update the Readme with information for running the new unit tests

**Comment by Urton-Ian28** [comment]
Go through and add system prints to show successful tests

**Comment by Urton-Ian28** [comment]
Closed by #394
