### ISSUE TITLE
Changing profile photo requires backing out of process

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapiStonsker#331]
The profile picture should be updated right after user uploads. Right now the user has to click "back" a bunch of times

https://user-images.githubusercontent.com/228704/161613528-8f716b34-d4f6-4523-82f2-8e4227ced2bd.mp4

**Comment by Urton-Ian28** [comment]
Bug occurs when tapping the profile picture to switch the photo, and every so often when changing the picture through the Edit Profile Page. Waiting before returning to the Account page from Edit Profile correctly updates the photo. Maybe switch to using a Provider for the image stream? This should also solve the updating through tapping the profile picture. The stream will rebuild everything correctly when the provider gets the update. 
Also, should we keep the profile photo updating from two separate places, or switch to either on the Edit Profile Page or tapping the picture.
