### ISSUE TITLE
Some markers should have images

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapiStonsker#335]
Being all-text is boring. Images would make the app really awesome. Famous places need an image to go with them 📸 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/228704/161620919-e60eafc4-a0c9-49ef-8397-d8fc29565d5d.png">

**Comment by MattyD797** [comment]
@Urton-Ian28 I'm not seeing the images in the markers?
![image](https://user-images.githubusercontent.com/69335573/164279451-cd191107-614e-440d-88b8-9d769bead78c.png)

**Comment by Urton-Ian28** [comment]
Not a marker with an image. 

Those markers are:
MANIGAULT'S FUNERAL HOME/CONGAREE CASKET COMPANY
RICHARDSON STREET/THE NORTH-SOUTH STREETS IN THE CITY OF COLUMBIA
GERVAIS STREET/THE EAST-WEST STREETS IN THE CITY OF COLUMBIA
COLLEGE STREET
BLOSSOM STREET
THE STATE HOUSE
TOWN THEATRE

**Comment by MattyD797** [comment]
you right
