### ISSUE TITLE
Persistent Friend Request

### ISSUE THREAD

**Issue by maskossen** [SCCapstone/CapiStonsker#374]
After the first user sends a request out to the second user, the second user can press the accept or deny as many times as they want:

![PersistantRequest](https://user-images.githubusercontent.com/45297361/163736317-196ecd9f-9d73-4c71-b536-56b0f2ce222f.gif)

This can lead to the second user accepting the request and then before leaving the Friends Page can press the deny button causing the two user's to be deleted from each other's list respectively:

https://user-images.githubusercontent.com/45297361/163736427-f0d14f87-9bdc-4bee-b3bf-b08bd890c840.mp4

**Comment by Urton-Ian28** [comment]
Thanks Mason! This issue should hopefully be resolved by PR #375. I'm not able to test on two emulators at once like this, but if you would be able to try it again and let me know that would be great. I'll hold off on closing the issue for now.

**Comment by maskossen** [comment]
Of course! I'll download and build with the source code that has the changes made and let you know. It might be a bit before I can report back since I'll have to download Flutter's and Dart's respective SDKs.

**Comment by maskossen** [comment]
@Urton-Ian28 Sorry in the delay I had some troubles getting Flutter to work with my Android Studio, after building from PR #375 it seems to still be an issue. Although now it seems like it is the accept button that is causing the problems since after hitting the deny button it instantly goes away.

https://user-images.githubusercontent.com/45297361/163748506-61c52e2c-2d70-4c2f-9ca2-f1089a110a6d.mp4
