### ISSUE TITLE
Honors thesis question

### ISSUE THREAD

**Issue by jamesdavis12** [SCCapstone/CapiStonsker#382]
For the honors thesis, do we need to get you to physically sign the title page? I see that some of the examples from previous years have your signature and was wondering if we need to talk to you about that before we submit the paper

![image](https://user-images.githubusercontent.com/55004488/164041821-53baf0ad-fe4f-4d30-8ceb-a6969686967f.png)

**Comment by josemvidal** [comment]
Correct.
