### ISSUE TITLE
Honors Thesis Advisor Signature

### ISSUE THREAD

**Issue by Urton-Ian28** [SCCapstone/CapiStonsker#405]
[Interactive SC Historical Map Application by CapiStonsker.pdf](https://github.com/SCCapstone/CapiStonsker/files/8563689/Interactive.SC.Historical.Map.Application.by.CapiStonsker.pdf)

Please sign and return this for our honors thesis as soon as you can. Thanks!

**Comment by josemvidal** [comment]
emailed it.
